import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Еврок - Figma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="header_left">
          <hr />
          <br />
          <h1>
            Аренда спецтехники <br />
            Liebherr для любых задач
          </h1>
          <br />
          <p>
            Мобильные, гусеничные и башенные краны <br />
            LIEBHERR в аренду для любых задач и грузов. <br />
            работаем по всей России
          </p>
          <br />
          <div className="header_left_zakaz">
            <button className="header_left_zakaz_btn1">Заказать звонок</button>
            <button className="header_left_zakaz_btn2">Каталог техники</button>
          </div>
        </div>
        <div className="header_right"></div>
      </header>
      <br />
      <br />
      <br />
      <section className="section1">
        <div className="container">
          <div className="section_main">
            <div className="section_main_left">
              <h2>
                <b>Спецтехника</b> в аренду
              </h2>
              <br />
              <Image src="/left2.png" fill />
            </div>
            <div className="section_main_right">
              <h1>Гусеничные краны</h1>
              <br />
              <p>
                Аренда гусеничного крана – актуальная услуга для многих <br />
                строительных площадок. Использование спецтехники <br />
                существенно упрощает погрузку - выгрузку материалов, <br />
                оптимизирует рабочий процесс.
              </p>
              <br />
              <button className="btn">Выбрать спецтехнику</button>
              <br />
              <Image src="/right2.svg" fill />
            </div>
          </div>
        </div>
      </section>
      <aside>
        <div className="container">
          <div className="aside_main">
            <h1 style={{ fontSize: "40px" }}>С нами надежно</h1>
            <br />
            <br />
            <div className="aside_main2">
              <div className="aside_main_left">
                Компания Еврокран успешно работает на территории РФ с 2000{" "}
                <br />
                года. <br />
                <br />
                В нашем автопарке гусеничные и мобильные краны известного <br />
                немецкого бренда. <br />
                <br />
                Среди них есть модели любой грузоподъемности, для погрузочных,
                <br />
                монтажных, транспортировочных и других работ. <br />
                <br />
                Обращение в компанию гарантирует комплексный подход к <br />
                решению поставленных задач. Получить больше информации <br />
                можно у менеджеров Компании Еврокран.
                <br />
                <br />
                <button className="btn">Заказать звонок </button>
              </div>
              <div className="aside_main_right">
                <Image src="/dg.svg" fill />
              </div>
            </div>
          </div>
        </div>
      </aside>
      <div className="main">
        <Image src="/d1.svg" fill />
      </div>
      <section className="section2">
        <h1>Каталог техники</h1>
        <div className="section_main2">
          <div className="section_main2_card">
            <Image src="/c1.png" fill />
            <br />
            <h2>
              Гусеничный кран <br />
              Liebherr LR 1750
            </h2>
            <hr />
            <br />
            <p>
              Грузоподъемность: 40 тонн <br />
              Длина стрелы: 35 м <br />
              <b>Все характеристики</b>
            </p>
            <br />
            <button className="btn">Арендовать</button>
          </div>
          <div className="section_main2_card">
            <Image src="/c1.png" fill />
            <br />
            <h2>
              Гусеничный кран <br />
              Liebherr LR 1750
            </h2>
            <hr />
            <br />
            <p>
              Грузоподъемность: 40 тонн <br />
              Длина стрелы: 35 м <br />
              <b>Все характеристики</b>
            </p>
            <br />
            <button className="btn">Арендовать</button>
          </div>
          <div className="section_main2_card">
            <Image src="/c1.png" fill />
            <br />
            <h2>
              Гусеничный кран <br />
              Liebherr LR 1750
            </h2>
            <hr />
            <br />
            <p>
              Грузоподъемность: 40 тонн <br />
              Длина стрелы: 35 м <br />
              <b>Все характеристики</b>
            </p>
            <br />
            <button className="btn">Арендовать</button>
          </div>
          <div className="section_main2_card">
            <Image src="/c1.png" fill />
            <br />
            <h2>
              Гусеничный кран <br />
              Liebherr LR 1750
            </h2>
            <hr />
            <br />
            <p>
              Грузоподъемность: 40 тонн <br />
              Длина стрелы: 35 м <br />
              <b>Все характеристики</b>
            </p>
            <br />
            <button className="btn">Арендовать</button>
          </div>
        </div>
        <div className="bbbtn">
          <button className="bbtn">Перейти в каталог</button>
        </div>
      </section>
      <br />
      <div className="wrap">
        <div className="container">
          <div className="wrap_main">
            <h1>Из чего складывается стоимость аренды</h1>
            <br />
            <br />
            <div className="wrap_main_wrapper">
              <div className="wrap_main_wrapper_card">
                <h2>01</h2>
                <br />
                <p>
                  Стоимость аренды крана <br />
                  определяется так: 8 (восемь) <br />
                  часов работы каждой единицы <br />
                  спецтехники в течение смены.
                </p>
              </div>
              <div className="wrap_main_wrapper_card">
                <h2>02</h2>
                <br />
                <p>
                  Стоимость аренды крана <br />
                  определяется так: 8 (восемь) <br />
                  часов работы каждой единицы <br />
                  спецтехники в течение смены.
                </p>
              </div>
              <div className="wrap_main_wrapper_card">
                <h2>03</h2>
                <br />
                <p>
                  Стоимость аренды крана <br />
                  определяется так: 8 (восемь) <br />
                  часов работы каждой единицы <br />
                  спецтехники в течение смены.
                </p>
              </div>
              <div className="wrap_main_wrapper_card">
                <h2>04</h2>
                <br />
                <p>
                  Стоимость аренды крана <br />
                  определяется так: 8 (восемь) <br />
                  часов работы каждой единицы <br />
                  спецтехники в течение смены.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br />
      <br />
      <div className="login">
        <hr />
        <div className="container">
          <div className="login_main">
            <br />
            <br />
            <h2>
              <b>Оперативно</b> поставим технику
            </h2>
            <br />
            <br />
            <div className="login_main_log">
              <input type="text" placeholder="Ваше имя" />
              <input type="text" placeholder="Ваш телефон*" />
              <button className="btn">Заказать звонок</button>
            </div>
            <br />
            <p>
              <input type="checkbox" /> Я согласен с условиями обработки и
              использования моих персональных данных
            </p>
            <br />
            <br />
          </div>
        </div>
        <hr />
      </div>
      <br />
      <br />
      <br />
      <br />
      <br />
      <section className="section3">
        <div className="container">
          <div className="section3_main">
            <div className="section3_main_left">
              <h1>О нас</h1>
              <br />
              <p>
                Компания ЕвроКран – это команда специалистов, <br />
                обеспечивающих эффективное использование <br />
                высокопроизводительных немецких автокранов марки LIEBHERR.{" "}
                <br />
                <br />
                Мы работаем с 2000 года и за это время не раз доказали свой{" "}
                <br />
                профессионализм и компетентность: сегодня нам доверяют <br />
                крупнейшие предприятия России.
                <br />
                <br />
                Мы обладаем собственным парком с более чем 50 единицами <br />
                техники и находимся в черте Москвы. Поэтому мы можем подать{" "}
                <br />
                любую технику в любую точку города незамедлительно, что <br />
                бывает весьма кстати в случае возникновения каких-либо <br />
                непредвиденных ситуаций.
              </p>
            </div>
            <div className="section3_main_right">
              <Image src="/r.png" fill />
            </div>
          </div>
        </div>
      </section>
      <section className="section4">
        <div className="container">
          <div className="section4_main">
            <h1>Услуги</h1>
            <div className="section_main_wrapper">
              <div className="section_main_wrapper_card">
                <Image src="/cr1.png" fill />
                <button>
                  Аренда мобильных автокранов <br />
                  Liebherr
                </button>
              </div>
              <div className="section_main_wrapper_card">
                <Image src="/cr2.png" fill />
                <button>
                  Аренда мобильных автокранов <br />
                  Liebherr
                </button>
              </div>
              <div className="section_main_wrapper_card">
                <Image src="/cr3.png" fill />
                <button>
                  Аренда мобильных автокранов <br />
                  Liebherr
                </button>
              </div>
              <div className="section_main_wrapper_card">
                <Image src="/cr4.png" fill />
                <button>
                  Аренда мобильных автокранов <br />
                  Liebherr
                </button>
              </div>
              <div className="section_main_wrapper_card">
                <Image src="/cr5.png" fill />
                <button>
                  Аренда мобильных автокранов <br />
                  Liebherr
                </button>
              </div>
              <div className="section_main_wrapper_card">
                <Image src="/cr6.png" fill />
                <button>
                  Аренда мобильных автокранов <br />
                  Liebherr
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div className="text">
        <div className="container">
          <div className="text_main">
            <br />
            <br />
            <br />
            <br />
            <h1>Аренда автокранов LIEBHERR в Москве</h1>
            <br />
            <br />
            <p>
              Аренда автокранов решает разные задачи. Благодаря большой
              грузоподъемности техника используется при установке и разборке{" "}
              <br />
              башенных кранов, строительстве мостовых пролетов, монтаже дымовых
              труб самонесущей конструкции, выполнении <br />
              аварийно-восстановительных работ в Москве.{" "}
            </p>
            <br />
            <br />
            <br />
            <h1>Аренда спецтехники Liebherr </h1>
            <br />
            <br />
            <br />
            <p>
              Liebherr («Либхерр») — известная немецкая машиностроительная
              компания. Ее автокраны востребованы во всем мире благодаря своим{" "}
              <br />
              уникальным возможностям. Основополагающие критерии их выбора —
              скорость и качество работы. Крупные строительные компании и <br />
              частные лица предпочитают арендовать строительные краны «Либхерр».
              Их выбор обусловлен надежностью, высокой <br />
              производительностью установок. Срок службы агрегатов исчисляется
              десятилетиями, на протяжении которых они сохраняют свои <br />
              характеристики и не теряют качества. <br />
              <br />
              На сегодняшний день мы реализовали сотни успешных проектов. Среди
              них: <br />
              <br />
              <button className="kub"></button> Предоставление автокрана
              Liebherr LR 1750 и автотрейлеров из собственного парка компании
              «Казметрострой». Техника <br />
              использовалась для демонтажа и перевозки проходческих щитов.{" "}
              <br />
              <br />
              <button className="kub"></button> Участие автокрана Liebherr LR
              1750 и автотрейлеров в демонтаже проходческого щита на участке
              метрополитена от станции «Выхино» <br />
              до «Косино-Ухтомской». <br />
              <br />
              <button className="kub"></button> Использование Liebherr LTM 1500
              в качестве основной мощности для производства работ при возведении
              Лукомльской ГРЭС. В <br />
              качестве арендатора выступала китайская машиностроительная
              инжиниринговая компания. <br />
              <br />
              <button className="kub"></button> Аренда низкорамных тралов для транспортировки спецтехники
              официального дилера ТМ в России, компании ООО «Либхерр-Русланд».{" "}
              <br />
              <br />
              <button className="kub"></button> Установка нового реактора гидрокрекинга на территории завода ОАО
              «Уфанефтехим». <br />
              <br />
              <button className="kub"></button> Демонтаж старых и монтаж новых чиллеров на крыше здания Mail.ru.
              Арендатор — строительный холдинг КМТ. <br />
              <br />
              <button className="kub"></button> Монтаж мостовых балок на головном участке автомобильной скоростной
              дороги Москва-Санкт-Петербург, произведенный с <br />
              использованием кранов Liebherr. <br />
              <br />
              <button className="kub"></button> Транспортировка и установка проходческого щита из Протвино в
              Москву для возведения Бутовской линии метрополитена. Заказ <br />
              выполнен компанией «Транстоннельстрой». <br />
              <br />
              Условия аренды оговариваются индивидуально. География
              предоставления услуги — Москва, Санкт-Петербург, Екатеринбург,
              Нижний <br />
              Новгород, Пермь, Воронеж, Челябинск, Краснодар, Ярославль, Самара,
              Уфа и другие города РФ. <br />
              <br />
            </p>
          </div>
        </div>
      </div>
      <div className="map">
        <Image src="/map.png" fill />
      </div>
    </>
  );
}
